# Generated by Django 5.0.6 on 2024-07-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('python_version', models.TextField()),
                ('required_libraries', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
    ]
