# Generated by Django 5.0.6 on 2024-07-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('time', models.TextField()),
                ('date', models.TextField()),
                ('description', models.TextField()),
                ('select', models.TextField()),
            ],
        ),
    ]
