# Generated by Django 5.0.6 on 2024-07-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('city', models.TextField()),
                ('pin_code', models.TextField()),
                ('colony', models.TextField()),
                ('house_number', models.TextField()),
                ('district', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
    ]
