# Generated by Django 5.0.6 on 2024-07-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('username', models.TextField()),
                ('section', models.TextField()),
                ('issue', models.TextField()),
                ('email', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
